version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - '/Users/danielmacedodeoliveira/dev/projetosEstudos/Spring e Keycloak Autenticação e Autorização com Segurança  '
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    ports:
     - 3333:5432
    networks:
      - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES # qual tipo de banco que o keycloak vai se conectar.
      DB_ADDR: postgres # o nome do servico da estrutura dos conteiner. 
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: keycloak_schema # nome do schema que foi criado no arquivo 
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge